"""adiciona campo pronto em itens

Revision ID: 00d0cdb3968b
Revises: cb4b44094658
Create Date: 2026-06-15 09:43:47.787480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d0cdb3968b'
down_revision = 'cb4b44094658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronto', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_itens', schema=None) as batch_op:
        batch_op.drop_column('pronto')

    # ### end Alembic commands ###
