"""Atualizado

Revision ID: 044baed2c578
Revises: 1134d8ca2f52
Create Date: 2026-04-18 22:18:17.721524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044baed2c578'
down_revision = '1134d8ca2f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uso_ilimitado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('uso_por_usuario', sa.Boolean(), nullable=True))
        batch_op.alter_column('qtd_cupons',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.alter_column('qtd_cupons',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('uso_por_usuario')
        batch_op.drop_column('uso_ilimitado')

    # ### end Alembic commands ###
