"""Adiciona um rótulo aos arquivos de tutoriais

Revision ID: 08de4a999b6c
Revises: 24c61881db06
Create Date: 2026-07-22 23:13:40.798581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08de4a999b6c'
down_revision = '24c61881db06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Conteudos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Conteudos', schema=None) as batch_op:
        batch_op.drop_column('arquivo')

    # ### end Alembic commands ###
