"""melhorando cupons

Revision ID: 1134d8ca2f52
Revises: 8f7af0b18596
Create Date: 2026-04-18 16:37:43.819267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1134d8ca2f52'
down_revision = '8f7af0b18596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.alter_column('cupom_expira',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.alter_column('cupom_expira',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
