"""Adicionado atendente ao chamado

Revision ID: 19abe8a6912f
Revises: e2ec15aaed61
Create Date: 2026-05-21 14:54:47.393097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19abe8a6912f'
down_revision = 'e2ec15aaed61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atendente', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('atendente')

    # ### end Alembic commands ###
