"""Adiciona status interno 'promovido' às peças mais antigas

Revision ID: 24c61881db06
Revises: ed0a60e5c441
Create Date: 2026-07-22 17:08:09.770277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c61881db06'
down_revision = 'ed0a60e5c441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promovido', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.drop_column('promovido')

    # ### end Alembic commands ###
