"""correções

Revision ID: 275d2a31c6ef
Revises: 9432be273b96
Create Date: 2026-04-08 12:45:47.735143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275d2a31c6ef'
down_revision = '9432be273b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuaria', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuaria'], ['Clientes.id_usuaria'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['Produtos.id_acessorio'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_itens')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
