"""Corrige definitivamente os pedidos

Revision ID: 2900fa445b70
Revises: 9a4c062feeec
Create Date: 2026-06-21 14:15:37.557922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2900fa445b70'
down_revision = '9a4c062feeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('usuaria',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('envio',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('data_entrega',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('data_pedido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pedido', sa.DATETIME(), nullable=True))
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('data_entrega',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('envio',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('usuaria',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
