"""Adiciona coluna para tatus nline à tabela das clientes

Revision ID: 33aca3394abe
Revises: 38141e80301f
Create Date: 2026-06-26 11:00:53.163856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33aca3394abe'
down_revision = '38141e80301f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_atividade', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.drop_column('ultima_atividade')

    # ### end Alembic commands ###
