"""Recloca data no pedido

Revision ID: 38141e80301f
Revises: 2900fa445b70
Create Date: 2026-06-21 15:34:37.399482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38141e80301f'
down_revision = '2900fa445b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pedido', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('data_pedido')

    # ### end Alembic commands ###
