"""Adicionando tabela de visualização nos produtos 

Revision ID: 47ec2d6332b3
Revises: 88a5c18fb002
Create Date: 2026-05-27 13:00:06.340272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ec2d6332b3'
down_revision = '88a5c18fb002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('data_visualizacao', sa.DateTime(), nullable=True),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['Clientes.id_usuaria'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['Produtos.id_acessorio'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('views_produto')
    # ### end Alembic commands ###
