"""add categoria

Revision ID: 5373c62cdf6b
Revises: 7e0f1d5503d8
Create Date: 2026-03-24 16:08:02.511857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5373c62cdf6b'
down_revision = '7e0f1d5503d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
