"""Adicioando Token de reset de senha

Revision ID: 5c84ec8a934e
Revises: 703289b6e09b
Create Date: 2026-03-31 22:07:23.121924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c84ec8a934e'
down_revision = '703289b6e09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_reset', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('token_expira', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.drop_column('token_expira')
        batch_op.drop_column('token_reset')

    # ### end Alembic commands ###
