"""Adicionando cupons de desconto

Revision ID: 60dc9d53bd14
Revises: c4eb93dab11c
Create Date: 2026-04-17 10:13:14.038766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dc9d53bd14'
down_revision = 'c4eb93dab11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupons',
    sa.Column('id_cupom', sa.Integer(), nullable=False),
    sa.Column('nome_cupom', sa.String(length=20), nullable=False),
    sa.Column('qtd_cupons', sa.Integer(), nullable=False),
    sa.Column('cupom_expira', sa.DateTime(), nullable=False),
    sa.Column('valor_desconto', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('usos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cupom'),
    sa.UniqueConstraint('nome_cupom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupons')
    # ### end Alembic commands ###
