"""initial clean

Revision ID: 7e0f1d5503d8
Revises: 
Create Date: 2026-03-20 09:48:14.649729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0f1d5503d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Banners',
    sa.Column('id_banner', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_banner')
    )
    op.create_table('Clientes',
    sa.Column('id_usuaria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('senha', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuaria'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Colecoes',
    sa.Column('id_colecao', sa.Integer(), nullable=False),
    sa.Column('capa_colecao', sa.String(length=255), nullable=False),
    sa.Column('nome_colecao', sa.String(length=50), nullable=False),
    sa.Column('tipo_foto', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_colecao'),
    sa.UniqueConstraint('capa_colecao')
    )
    op.create_table('Produtos',
    sa.Column('id_acessorio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('colecao_id', sa.Integer(), nullable=True),
    sa.Column('tamanho', sa.String(length=20), nullable=True),
    sa.Column('material', sa.String(length=20), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'VENDIDO', name='status_acessorio'), nullable=False),
    sa.Column('tipo_foto', sa.String(length=50), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('em_estoque', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['Colecoes.id_colecao'], ),
    sa.PrimaryKeyConstraint('id_acessorio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Produtos')
    op.drop_table('Colecoes')
    op.drop_table('Clientes')
    op.drop_table('Banners')
    # ### end Alembic commands ###
