"""Adicionando tabela de cupons usados

Revision ID: 88a5c18fb002
Revises: 19abe8a6912f
Create Date: 2026-05-24 12:51:12.019147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a5c18fb002'
down_revision = '19abe8a6912f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usos_cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['Clientes.id_usuaria'], ),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id_cupom'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usos_cupons')
    # ### end Alembic commands ###
