"""Adicionando melhoria nos cupons

Revision ID: 8f7af0b18596
Revises: 60dc9d53bd14
Create Date: 2026-04-18 14:18:20.083658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7af0b18596'
down_revision = '60dc9d53bd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('data_resgate', sa.DateTime(), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id_cupom'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Clientes.id_usuaria'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_cupom')
    # ### end Alembic commands ###
