"""Correções

Revision ID: 9432be273b96
Revises: 5c84ec8a934e
Create Date: 2026-04-03 15:11:20.046335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9432be273b96'
down_revision = '5c84ec8a934e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_foto', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['Produtos.id_acessorio'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               nullable=False)

    with op.batch_alter_table('Colecoes', schema=None) as batch_op:
        batch_op.drop_column('tipo_foto')

    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.drop_column('imagem')
        batch_op.drop_column('tipo_foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_foto', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('Colecoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_foto', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               nullable=True)

    op.drop_table('produtos_imagens')
    # ### end Alembic commands ###
