"""Adiciona registro do cupom usado no pedido

Revision ID: 9a4c062feeec
Revises: df8c08d7ab65
Create Date: 2026-06-20 11:29:26.314734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4c062feeec'
down_revision = 'df8c08d7ab65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupom_usado', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('cupom_usado')

    # ### end Alembic commands ###
