"""Adicionando curtias aos produos

Revision ID: ac472d43cdf4
Revises: 044baed2c578
Create Date: 2026-05-16 10:02:04.319000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac472d43cdf4'
down_revision = '044baed2c578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
      batch_op.add_column(
        sa.Column(
          'curtidas',
          sa.Integer(),
          nullable=False,
          server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Produtos', schema=None) as batch_op:
        batch_op.drop_column('curtidas')

    # ### end Alembic commands ###
