"""Adicionando histórico do chatbot

Revision ID: b77fe51454f3
Revises: ac472d43cdf4
Create Date: 2026-05-19 11:38:17.031757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77fe51454f3'
down_revision = 'ac472d43cdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamados',
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id_usuaria'], ),
    sa.PrimaryKeyConstraint('id_chamado')
    )
    op.create_table('Mensagens',
    sa.Column('id_mensagem', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('remetente', sa.String(length=20), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id_chamado'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id_usuaria'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Mensagens')
    op.drop_table('chamados')
    # ### end Alembic commands ###
