"""Adicionado Estado no endereço

Revision ID: c4eb93dab11c
Revises: d45765ba95e3
Create Date: 2026-04-11 12:57:01.848497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4eb93dab11c'
down_revision = 'd45765ba95e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
