"""Adiciona colunas de forma de pagamento e rastreio aos pedidos

Revision ID: cb4b44094658
Revises: d8a8f302c1ab
Create Date: 2026-06-02 11:17:55.652234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4b44094658'
down_revision = 'd8a8f302c1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('codigo_rastreio', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('codigo_rastreio')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
