"""Adicionando endereço

Revision ID: d45765ba95e3
Revises: 275d2a31c6ef
Create Date: 2026-04-11 12:22:47.889904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45765ba95e3'
down_revision = '275d2a31c6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('rua', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id_usuaria'], ),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enderecos')
    # ### end Alembic commands ###
