"""adiciona envio e data_entrega

Revision ID: d8a8f302c1ab
Revises: 47ec2d6332b3
Create Date: 2026-06-02 00:20:18.309232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a8f302c1ab'
down_revision = '47ec2d6332b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('envio')

    # ### end Alembic commands ###
