"""Adiciona status de produção aos items

Revision ID: df8c08d7ab65
Revises: 00d0cdb3968b
Create Date: 2026-06-15 10:10:30.369286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8c08d7ab65'
down_revision = '00d0cdb3968b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_producao', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_itens', schema=None) as batch_op:
        batch_op.drop_column('status_producao')

    # ### end Alembic commands ###
