"""restaurando models chat

Revision ID: e2ec15aaed61
Revises: b77fe51454f3
Create Date: 2026-05-21 14:27:00.354848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ec15aaed61'
down_revision = 'b77fe51454f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Mensagens', schema=None) as batch_op:
        batch_op.drop_column('data_resposta')

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('Mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_resposta', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
