"""Adiciona coluna de telefone à cliente. 

Revision ID: e937cb787dfb
Revises: 08de4a999b6c
Create Date: 2026-07-25 15:07:30.733753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e937cb787dfb'
down_revision = '08de4a999b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fone', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.drop_column('fone')

    # ### end Alembic commands ###
