"""Cria tabela especìfica de conteúdos (posts no geral) 

Revision ID: ed0a60e5c441
Revises: 33aca3394abe
Create Date: 2026-07-13 12:09:31.967431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0a60e5c441'
down_revision = '33aca3394abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conteudos',
    sa.Column('id_conteudo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_conteudo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Conteudos')
    # ### end Alembic commands ###
